### ISSUE TITLE
Separate dependencies/config file

### ISSUE THREAD

**Issue by rkoch** [hyPiRion/inlein#14]
I'm doing a lot of work in inlein scripts by now. I split my scripts up into multiple files, as I have some common stuff functions which are used in multiple entrypoints (executable scripts). So far so good, I created a function in every script which locates the directory of the current script and loads the common files through `(load-file)`:

``` clj
(defn pwd [] (->> (meta #'pwd) :file (java.io.File.) (.getParent)))
(let [wd (pwd)]
  (load-file (str wd "/_config.clj"))
  (load-file (str wd "/utils/_files.clj")))
```

Now sometimes these common files have specific dependencies such as `[org.clojure/data.xml]` or `[plumatic/schema]` and I don't want to define dependencies in each and every script because sometimes I forget to add a dependency or switch versions. I have 30+ scripts depending on these common scripts.

To fix this problem I thought it would be nice to have a separate dependencies file (e.g. `.inlein-deps`) in the same folder as the script which inlein would look for when there is no dependency map in the script.

What's your opinion on that?

**Comment by hyPiRion** [comment]
Yeah, I would like to make this easier. =)

I've had the same issue with bash scripts: You have a lot of common utility functions/stuff that you would like share, so you sensibly enough source it with the correct location of that file. Obviously that's no good for dependency resolution.

I'm not sure if a separate `.inlein-deps` file is the best option here though: I think it would be better if we could rather specify files that we "source", and then Inlein handles dependency resolution for us in addition.

So say you have two files: `foo.clj` and `bar.clj`. `foo.clj` looks like this:

```clj
'{:dependencies [[org.clojure/clojure "1.8.0"]
                 [cheshire "5.5.0"]]}

(require '[cheshire.core :refer [generate-string]])

(defn foo [x]
  (generate-string {:content (+ x x)}))
```

then I would like to not only get `foo.clj`s dependencies, but also the source as well. So `bar.clj` could look like this:

```clj
'{:dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/math.combinatorics "0.1.1"]]
  :file-deps ["bar.clj"]}

(require '[clojure.math.combinatorics :as combo])

(println (generate-string (combo/subsets [1 2 3])))
(println (foo 10))
```

and that would print out what one would expect from those `printlns`.

That would also make future ideas (uberjaring scripts etc) a bit more compatible, as you can bundle the entire thing into uberjars.

Does that sound like a reasonable idea?

Also, for reference, you can use [pomegranate's `add-dependencies`](https://github.com/cemerick/pomegranate#add-classpath-usage) in the meantime as a workaround – if you only depend on pomegranate, then you can load the file, and then that file could also load the dependencies you need. It will not work for all cases, but at least it's worth looking into if you find copypasting dependencies a bit of a hassle as of right now.

**Comment by rkoch** [comment]
Whoa that would be neat!

With this inlein could automatically source the files in the correct order. With `(load-file)` I have to put the commands in the right order when some common-files depend on other common files.

One Issue that comes to mind is the correct dependency version when you have multiple files depend on the same artifact but different version. But that might easily be solved by just saying first wins or last wins.

**Comment by hyPiRion** [comment]
Yeah, I think sourcing should put priority on dependencies just like proper dependencies do. That shouldn't be hard to satisfy though.

**Comment by hyPiRion** [comment]
Resolved by 3b95d6fb04349341c224d7c2bbc03a7ec594aec0

**Comment by hyPiRion** [comment]
@rkoch: If this is still interesting for you, I have now implemented this into Inlein and it is supported by adding [:file-deps](https://github.com/hyPiRion/inlein/wiki/Parameter-Options#file-deps) to the parameter map inside the script. You just have to upgrade to version 0.2.0, which you can do by running the command `inlein --upgrade`.

**Comment by rkoch** [comment]
I just upgraded my scripts to use this and not my custom loader, seems to work well! Thank you for adding this!
