### ISSUE TITLE
unexpected EOF while looking for matching `''

### ISSUE THREAD

**Issue by ottonascarella** [hyPiRion/inlein#20]
Hi,

I wrote a "hello world" program:

```

#!/usr/bin/env inlein

'{:dependencies [[org.clojure/clojure "1.8.0"]]}

(println "Hello World!")

```

I am getting 2 error messages when calling ./hello-world.clj
./hello-world.clj: line 4: unexpected EOF while looking for matching `''
./hello-world.clj: line 7: syntax error: unexpected end of file

**Comment by hyPiRion** [comment]
Hi,

That's a strange result – I guess this may happen if you have an empty line as the first line in your file. Is that the case? And if so, would removing the empty line so that `#!/usr/bin/env inlein` is the first line help?

**Comment by ottonascarella** [comment]
SPOT ON!! That insidious line!

Thanks for the help!
