### ISSUE TITLE
Windows daemon doesn't run completely as a background process

### ISSUE THREAD

**Issue by hyPiRion** [hyPiRion/inlein#4]
Whenever you run this on Windows, the inlein daemon will be "bound" to the command prompt and will cause the prompt to hang on shutdown. And if you force-kill the prompt, then the `C:\Users\<username>\.inlein\port`-file will still be available, causing subsequent inlein calls to crash with an exception.

The code for starting the daemon is over at
https://github.com/hyPiRion/inlein/blob/b87acc814c5d832f48352bceb9190d10e50cdffd/client/src/inlein/client/ServerConnection.java#L42-L52 – and I'm guessing we'd have to add some magic for Windows users here to fix this.

**Comment by arrdem** [comment]
"any windows support is entirely accidental"
